"""
aura_semantic_core.py
Auto-generated by build.py -- AURA Semantic Core
Repository: TFrank42/aura-semantic-core
Build date: 2026-05-15
Vectors: 223 x 12D float32 (cosine-normalized)
Vocab: 223 tokens
"""

import math
import struct

DIMS = 12

VOCAB = {"the": 0, "a": 1, "and": 2, "to": 3, "of": 4, "is": 5, "in": 6, "it": 7, "you": 8, "that": 9, "he": 10, "she": 11, "we": 12, "they": 13, "have": 14, "has": 15, "be": 16, "been": 17, "were": 18, "was": 19}

ID_TO_TOKEN = {v: k for k, v in VOCAB.items()}

VECTORS = [
    (0.778499, 0.07785, 0.0, 0.0, 0.622799, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (0.777482, 0.172774, 0.0, 0.0, 0.604708, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (0.0, 0.780869, 0.0, 0.0, 0.0, 0.624695, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (0.0, 0.0, 0.743294, 0.0, 0.0, 0.0, 0.668965, 0.0, 0.0, 0.0, 0.0, 0.0),
    (0.0, 0.0, 0.0, 0.780869, 0.0, 0.0, 0.0, 0.624695, 0.0, 0.0, 0.0, 0.0),
    (0.0, 0.0, 0.0, 0.0, 0.743294, 0.0, 0.0, 0.0, 0.668965, 0.0, 0.0, 0.0),
    (0.0, 0.0, 0.468293, 0.468293, 0.0, 0.0, 0.0, 0.0, 0.0, 0.749269, 0.0, 0.0),
    (0.436852, 0.0, 0.0, 0.0, 0.436852, 0.0, 0.0, 0.0, 0.0, 0.0, 0.786334, 0.0),
    (0.0, 0.0, 0.0, 0.0, 0.0, 0.668965, 0.0, 0.0, 0.0, 0.0, 0.0, 0.743294),
    (0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.5, 0.0, 0.0),
    (0.0, 0.0, 0.0, 0.624695, 0.0, 0.0, 0.0, 0.0, 0.780869, 0.0, 0.0, 0.0),
    (0.0, 0.0, 0.0, 0.624695, 0.0, 0.0, 0.0, 0.0, 0.0, 0.780869, 0.0, 0.0),
    (0.0, 0.449013, 0.0, 0.449013, 0.0, 0.628619, 0.0, 0.0, 0.0, 0.0, 0.449013, 0.0),
    (0.0, 0.449013, 0.0, 0.449013, 0.0, 0.0, 0.628619, 0.0, 0.0, 0.0, 0.0, 0.449013),
    (0.0, 0.0, 0.707107, 0.0, 0.707107, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (0.0, 0.0, 0.754829, 0.0, 0.646997, 0.0, 0.0, 0.107833, 0.0, 0.0, 0.0, 0.0),
    (0.174078, 0.0, 0.696311, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.696311, 0.0),
    (0.184115, 0.0, 0.73646, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.644402, 0.092057),
    (0.0, 0.0, 0.643268, 0.107211, 0.0, 0.536056, 0.0, 0.0, 0.0, 0.0, 0.536056, 0.0),
    (0.0, 0.0, 0.679366, 0.113228, 0.452911, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.566139),
]


def _dot(a, b):
    return sum(x * y for x, y in zip(a, b))


def _norm(v):
    n = math.sqrt(sum(x * x for x in v))
    return n if n > 0 else 1.0


def _cosine(a, b):
    return _dot(a, b) / (_norm(a) * _norm(b))


class AuraSemanticCore:
    """
    Lightweight semantic embedding engine backed by AURA brain vectors.

    Usage:
        from aura_semantic_core import AuraSemanticCore
        core = AuraSemanticCore()
        vec  = core.get_vector('the')
        hits = core.most_similar('he', topn=5)
        emb  = core.encode('she and he')
        sim  = core.sentence_similarity('he was', 'she was')

    To use the full 32,000-vector brain, pass bin_path to __init__:
        core = AuraSemanticCore(bin_path='aura_brain.bin')
    """

    def __init__(self, bin_path=None):
        self.vocab = VOCAB
        self.id_to_token = ID_TO_TOKEN
        self.dim = DIMS
        self.vocab_size = len(VOCAB)
        if bin_path:
            self.vectors = self._load_bin(bin_path)
        else:
            self.vectors = VECTORS

    def _load_bin(self, path):
        with open(path, 'rb') as f:
            raw = f.read()
        nf = len(raw) // 4
        fl = struct.unpack(f'{nf}f', raw[:nf * 4])
        return [tuple(fl[i * self.dim:(i + 1) * self.dim]) for i in range(nf // self.dim)]

    def get_vector(self, token):
        """Return the 12D embedding for a token, or None if OOV."""
        idx = self.vocab.get(token)
        if idx is None or idx >= len(self.vectors):
            return None
        return self.vectors[idx]

    def most_similar(self, token, topn=5):
        """Return top-N most similar tokens by cosine similarity."""
        qvec = self.get_vector(token)
        if qvec is None:
            return []
        scores = []
        for tok, idx in self.vocab.items():
            if tok == token or idx >= len(self.vectors):
                continue
            sim = _cosine(qvec, self.vectors[idx])
            scores.append((sim, tok))
        scores.sort(reverse=True)
        return [(tok, round(sim, 6)) for sim, tok in scores[:topn]]

    def encode(self, text):
        """Mean-pool word vectors for a whitespace-tokenized sentence."""
        tokens = text.lower().split()
        vecs = [self.get_vector(t) for t in tokens if self.get_vector(t) is not None]
        if not vecs:
            return tuple([0.0] * self.dim)
        mean = tuple(sum(v[i] for v in vecs) / len(vecs) for i in range(self.dim))
        n = _norm(mean)
        return tuple(x / n for x in mean)

    def sentence_similarity(self, text_a, text_b):
        """Cosine similarity between two sentences."""
        return round(_cosine(self.encode(text_a), self.encode(text_b)), 6)

    def __repr__(self):
        return f'AuraSemanticCore(vocab_size={self.vocab_size}, dim={self.dim}, vectors={len(self.vectors)})'
