#!/usr/bin/env python3
"""
build.py — AURA Semantic Core Build Script
==========================================
Repo: https://github.com/TFrank42/aura-semantic-core

Steps
-----
1. Download raw artifacts from GitHub (tokenizer.json + aura_brain.bin)
2. Validate & parse the tokenizer vocab
3. Load and validate the 12D brain vectors
4. Auto-detect embedding dimensions from .bin file
5. Generate aura_semantic_core.py — a fully usable Python module
6. Run a smoke-test (cosine similarity lookup)
"""

import os
import sys
import json
import struct
import math
import time
import urllib.request

# Config
REPO_RAW = "https://raw.githubusercontent.com/TFrank42/aura-semantic-core/main"
ARTIFACTS = {
    "tokenizer.json": f"{REPO_RAW}/tokenizer.json",
    "aura_brain.bin": f"{REPO_RAW}/aura_brain.bin",
}
BUILD_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_MODULE = os.path.join(BUILD_DIR, "aura_semantic_core.py")

def log(step, msg):
    print(f"  [{step}] {msg}")

def section(title):
    print(f"\n{'=' * 60}")
    print(f"  {title}")
    print(f"{'=' * 60}")

def download(name, url, dest):
    log("GET", url)
    t0 = time.time()
    urllib.request.urlretrieve(url, dest)
    size = os.path.getsize(dest)
    elapsed = time.time() - t0
    log("OK", f"Saved {name} ({size:,} bytes, {elapsed:.2f}s)")
    return dest

def cosine(a, b):
    dot = sum(x * y for x, y in zip(a, b))
    mag_a = math.sqrt(sum(x * x for x in a))
    mag_b = math.sqrt(sum(x * x for x in b))
    if mag_a == 0 or mag_b == 0:
        return 0.0
    return dot / (mag_a * mag_b)

# Step 1: Download
section("STEP 1 - Downloading artifacts")
paths = {}
for name, url in ARTIFACTS.items():
    dest = os.path.join(BUILD_DIR, name)
    paths[name] = download(name, url, dest)

# Step 2: Parse tokenizer
section("STEP 2 - Parsing tokenizer.json")
with open(paths["tokenizer.json"], "r", encoding="utf-8") as f:
    tok_raw = json.load(f)

if "model" in tok_raw and "vocab" in tok_raw["model"]:
    vocab = tok_raw["model"]["vocab"]
    log("Schema", "Nested format: model.vocab")
elif "vocab" in tok_raw:
    vocab = tok_raw["vocab"]
    log("Schema", "Flat format: vocab")
else:
    vocab = tok_raw
    log("Schema", "Top-level dict used as vocab")

vocab_size = len(vocab)
id_to_tok = {v: k for k, v in vocab.items()}
log("OK", f"Vocab size: {vocab_size:,} tokens")
log("Sample", f"First 5: {list(vocab.items())[:5]}")

# Step 3: Load brain vectors
section("STEP 3 - Loading aura_brain.bin")
bin_size = os.path.getsize(paths["aura_brain.bin"])
log("File", f"{bin_size:,} bytes")

FLOAT_SIZE = 4
candidate_dims = [12, 16, 32, 64, 128, 8, 24, 48, 256]
detected_dims = None
detected_n = None

for d in candidate_dims:
    if bin_size % (d * FLOAT_SIZE) == 0:
        detected_dims = d
        detected_n = bin_size // (d * FLOAT_SIZE)
        break

if detected_dims is None:
    for d in range(1, 1025):
        if bin_size % (d * FLOAT_SIZE) == 0:
            detected_dims = d
            detected_n = bin_size // (d * FLOAT_SIZE)
            break

if detected_dims is None:
    log("ERROR", "Cannot determine embedding dimensions.")
    sys.exit(1)

log("Dims", f"Detected: {detected_n:,} vectors x {detected_dims}D (float32)")

with open(paths["aura_brain.bin"], "rb") as f:
    raw_bytes = f.read()

n_floats = len(raw_bytes) // FLOAT_SIZE
floats = struct.unpack(f"{n_floats}f", raw_bytes[:n_floats * FLOAT_SIZE])
vectors = [list(floats[i * detected_dims:(i + 1) * detected_dims]) for i in range(detected_n)]

log("OK", f"Loaded {len(vectors):,} embedding vectors")

# Step 4: Generate aura_semantic_core.py
section("STEP 4 - Generating aura_semantic_core.py")

vocab_json = json.dumps(vocab, ensure_ascii=False)
module_lines = [
    '"""',
    'aura_semantic_core.py',
    'Auto-generated by build.py -- AURA Semantic Core',
    'Repo: https://github.com/TFrank42/aura-semantic-core',
    '"""',
    '',
    'import math, struct',
    '',
    f'DIMS = {detected_dims}',
    f'VOCAB = {vocab_json}',
    'ID_TO_TOK = {v: k for k, v in VOCAB.items()}',
    '',
    'def _cosine(a, b):',
    '    dot = sum(x*y for x,y in zip(a,b))',
    '    na = math.sqrt(sum(x*x for x in a))',
    '    nb = math.sqrt(sum(x*x for x in b))',
    '    return dot/(na*nb) if na and nb else 0.0',
    '',
    'class AuraSemanticCore:',
    '    def __init__(self, bin_path):',
    '        self.vocab = VOCAB',
    '        self.id_to_tok = ID_TO_TOK',
    '        self.dims = DIMS',
    '        with open(bin_path, "rb") as f: raw = f.read()',
    '        nf = len(raw)//4',
    '        fl = struct.unpack(f"{nf}f", raw[:nf*4])',
    '        self.vectors = [list(fl[i*DIMS:(i+1)*DIMS]) for i in range(nf//DIMS)]',
    '',
    '    def get_vector(self, token):',
    '        idx = self.vocab.get(token)',
    '        if idx is None or idx >= len(self.vectors): return None',
    '        return self.vectors[idx]',
    '',
    '    def most_similar(self, token, top_k=10):',
    '        vec = self.get_vector(token)',
    '        if vec is None: return []',
    '        scores = [(self.id_to_tok.get(i,f"token_{i}"), _cosine(vec,v))',
    '                  for i,v in enumerate(self.vectors)',
    '                  if self.id_to_tok.get(i) != token]',
    '        return sorted(scores, key=lambda x: x[1], reverse=True)[:top_k]',
    '',
    '    def encode(self, text):',
    '        vecs = [v for v in (self.get_vector(t) for t in text.lower().split()) if v]',
    '        if not vecs: return [0.0]*self.dims',
    '        return [sum(v[d] for v in vecs)/len(vecs) for d in range(self.dims)]',
    '',
    '    def sentence_similarity(self, a, b):',
    '        return _cosine(self.encode(a), self.encode(b))',
    '',
    '    def __repr__(self):',
    '        return f"AuraSemanticCore(vocab={len(self.vocab)}, vectors={len(self.vectors)}, dims={self.dims})"',
]

with open(OUT_MODULE, "w", encoding="utf-8") as f:
    f.write("\n".join(module_lines))
log("OK", f"Generated: {OUT_MODULE}")

# Step 5: Smoke test
section("STEP 5 - Smoke test")
import importlib.util
spec = importlib.util.spec_from_file_location("aura_semantic_core", OUT_MODULE)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)

aura = mod.AuraSemanticCore(paths["aura_brain.bin"])
log("Init", str(aura))
for word in ["the", "and", "is"]:
    v = aura.get_vector(word)
    if v:
        log(f"vec({word})", f"{[round(x,4) for x in v[:6]]}...")

log("most_similar('the')", "")
for tok, score in aura.most_similar("the", top_k=5):
    print(f"      {tok:<20} cosine={score:.4f}")

section("BUILD COMPLETE")
print(f"  Vocab: {vocab_size:,} tokens | Vectors: {len(vectors):,} x {detected_dims}D | Status: PASSED")
